
services:
  bridge:
    build: .
    container_name: max_telegram_bridge
    restart: always
    command: run_bridge
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
    env_file:
      - .env